In [1]:
# Load libraries
import numpy as np
from sklearn.preprocessing import Binarizer

In [2]:
# Create feature
age = np.array([[6],
[12],
[20],
[36],
[65]])

In [3]:
# Create binarizer
binarizer = Binarizer(threshold=18)

In [4]:
# Transform feature
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [5]:
# Bin feature
np.digitize(age, bins=[20,30,64])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [6]:
# Bin feature
np.digitize(age, bins=[20,30,64], right=True)

array([[0],
       [0],
       [0],
       [2],
       [3]])

In [7]:
# Bin feature
np.digitize(age, bins=[18])

array([[0],
       [0],
       [1],
       [1],
       [1]])